### ISSUE TITLE
name clash with existing moody-templates package.

### ISSUE THREAD

**Issue by PDoakORNL** [AndrewAnnex/moody#1]
It would be great if this didn't happen. import produces confusing results for novices when both packages are installed.

**Comment by AndrewAnnex** [comment]
@PDoakORNL 
so after seeing that this is as an issue on https://github.com/etianen/moody-templates/issues/12, I think 'moody-templates' should be updated to follow [pep 423](https://www.python.org/dev/peps/pep-0423/#use-a-single-name) by changing the package name there to match that used in the pip install command (ie`import moody-templates`).

**Comment by etianen** [comment]
I agree with @AndrewAnnex
